### ISSUE TITLE
Enhance the README.md for Firefox

### ISSUE THREAD

**Issue by XavCC** [Perdu/Cookie-Glasses#1]
Hi,

I just want to contribute to a more just writing of steps for a more fluid experience.

My proposal could be biased by my practices so let's talk about it if I in a wrong way. 

For Firefox, steps seems to be :
1. Download `https://github.com/Perdu/Cookie-Glasse` with the tool you like or with : 
![](https://i.imgur.com/GxOmjFh.png)
2. Unzip it in your computer in order to have a local repository like `<path>/.../Cookie-Glasse-master`
3. Go to browser in tab bar with `about:debugging#/runtime/this-firefox` 
4. Click "Load temporary addon"
5. Choose the `manifest.json` file in the `Cookie-Glasse-master` folder on your computer.
6. Visit websites implementing the Transparency & Consent Framework
7. Enjoy detecting violations!

---

`Cookie-Glasse-master` instead of `cookie_glasses`, 
+ cause `cookie_glasses` doesn't exist in the repo 
and 
+ `Cookie-Glasse-master` allow to update local repo with a simple `# git git pull origin master`

**Comment by Perdu** [comment]
Hi! Thanks for the hints, I updated the README.
For the record, the extension is still under submission on both addon stores. This would considerably simplify the install procedure if they got accepted.
