### ISSUE TITLE
Firefox 71.0 will not load addon

### ISSUE THREAD

**Issue by EliasA** [Perdu/Cookie-Glasses#2]
Firefox 71.0 won't load manifest.json any more. Claims that the file is broken. 

Works OK with Chromium 79.0.3945.79

Tested on Ubuntu 18.04

**Comment by Perdu** [comment]
I just tested on Firefox 71.0 and had no problem. Did you select the manifest.json file? What is the error message exactly?

**Comment by EliasA** [comment]
Sorry - my mistake! I used in error the "Install addon from file" function in addons menu. Using the method in documentation works flawlessly.
